parameters:
    elseym.content_type_negotiation.negotiator.class: elseym\ContentTypeNegotiationBundle\EventListener\ContentTypeNegotiator

services:
  elseym.content_type_negotiation.negotiator:
    class: %elseym.content_type_negotiation.negotiator.class%
    arguments: [@request, @logger]
    scope: request
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onController }
      - { name: monolog.logger, channel: request }